# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "f56c3dd58a43fd56211213e7c78f9301"
name = "Product Options and Terms"
application_url = "https://product-fields-terms.onrender.com"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_orders"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://product-fields-terms.onrender.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
